name: Deploy Azion MCP (STAGE)

on:
  workflow_dispatch:
  push:
    branches:
    - dev

permissions: {}

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    env:
      AZION_DEPLOY_STATE_BUCKET: ${{ secrets.AZION_DEPLOY_STATE_BUCKET }}
    steps:
    - name: Checkout code
      uses: actions/checkout@a37ce9120846195fa4ece8f58b268e6043cb2f26 # v3.7.0
      with:
        persist-credentials: false

    - name: Use Node.js 20.x
      uses: actions/setup-node@3235b876344d2a9aa001b8d1453c930bba69e610 # v3.9.1
      with:
        node-version: 20

    - name: Enable Corepack and prepare Yarn 1.x
      run: |
        corepack enable
        corepack prepare yarn@1.22.22 --activate

    - name: Install dependencies
      run: yarn install

    - name: Download Azion CLI
      run: |
        curl -o azionlinux https://downloads.azion.com/linux/x86_64/azion
        sudo mv azionlinux /usr/bin/azion
        sudo chmod u+x /usr/bin/azion

    - name: Configure Azion CLI
      env:
        AZION_TOKEN: ${{ secrets.AZION_TOKEN }}
      run: azion -t "$AZION_TOKEN"

    - name: Download Azion deploy state
      run: ./.github/scripts/azion-deploy-state.sh download --env stage

    - name: Build & Deploy
      run: BUILD_ENV=stage azion deploy --local --auto --debug --config-dir azion/stage

    - name: Upload Azion deploy state
      run: ./.github/scripts/azion-deploy-state.sh upload --env stage
